title: Abandoned Cart Documentation
description: Everything you want and need to know about this extension.
theme: just-the-docs
logo: "assets/plugin.png"

url: https://diztech-b-v.github.io/zeobv-s6-abandoned-cart/

aux_links:
  Store: http://store.shopware.com/en/search?sSearch=zeobv63525113392
